{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "SimiliarImages.serviceAccountName" . }}
  labels:
{{ include "SimiliarImages.labels" . | nindent 4 }}
{{- end -}}
